<head>
    <!--  (c) Mobile Site Deigned By:  subPRINT Interactive | Joe McCann | XHTML, CSS, jQuery, PHP, AJAX, Mobile, iPhone, Android, Blackberry | joe[at]subprint.com -->
		<title><?php echo $config[$page]['title']; ?></title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
    <meta name="robots" content="all" />
    <meta name="robots" content="index, follow" />
    <meta name="revisit-after" content="3 days" />
    <meta name="author" content="Joe McCann" />
    <meta http-equiv="imagetoolbar" content="no" />
    <meta name="mssmarttagspreventparsing" content="true" />
    <link href="css/styles.php" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="js/LAB.min.js">
    </script>
</head>
