<head>
    <!--  (c) Website Deigned By:  subPRINT Interactive | Joe McCann | XHTML, CSS, jQuery, PHP, AJAX, Mobile, iPhone, Android, Blackberry | joe[at]subprint.com -->
	<title>Fail Friday - All Bank Failures, Every Friday</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="Privatize the profits and socialize the losses! See the results of modern capitalism at its finest. All US bank failures updated in real time." />
    <meta name="language" content="en" />
    <meta name="copyright" content="Joe McCann - www.subprint.com" />
    <meta name="robots" content="all" />
    <meta name="robots" content="index, follow" />
    <meta name="revisit-after" content="1 days" />
    <meta http-equiv="imagetoolbar" content="no" />
    <meta name="mssmarttagspreventparsing" content="true" />
	<link rel="icon" type="image/vnd.microsoft.icon" href="img/favicon.ico" />
    <link href="css/styles.php" rel="stylesheet" type="text/css" media="all" />
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAA6RSvoCTy9i33pRfR0S5vYhSphy-KDRi91sGWceGOprT_0ke6NhRANgts_4egQGH8S7lJC6SFP4hkdw" type="text/javascript"></script>
    <script type="text/javascript" src="js/LAB.min.js">
    </script>
</head>
